spring:
    #4. Tạo định tuyến động
    cloud:
        gateway:
            server:
                webflux:
                    discovery:
                        locator:
                            enabled: true
                            lower-case-service-id: true
#1. Đặt port cho gateway-service
server:
    port: 8080
#2. Đăng ký với eureka
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
          defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true



